[tool.poetry]
name = "virtual-data"
version = "0.1.0"
description = ""
authors = ["HenriqueFreitas07 <henriquefreitasm87@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
kafka-python = "^2.0.2"
python-dotenv = "^1.0.1"

[tool.poetry.scripts]
virtual="virtual_data.generation:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
