services:
  mongo:
    image: mongo
    restart: unless-stopped
    env_file: .env

    environment:
      MONGO_INITDB_DATABASE: $DB_NAME

    volumes:
      - mongodb:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backend

  backend:
    depends_on:
      - mongo

    build:
      context: ./backend

    restart: on-failure
    env_file: .env

    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.application.name": "backend",
        "spring.data.mongodb.host": "mongo",
        "spring.data.mongodb.port": "27017",
        "spring.data.mongodb.database": "$DB_NAME",
        "security.jwt.secret-key": "$JWT_SECRET_KEY",
        "security.jwt.expiration-time": "$JWT_EXPIRATION_TIME",
        "springdoc.api-docs.path": "/api/v1/docs",
        "gemini.api-key": "$GEMINI_API_KEY",
        "google.search-api-key": "$GOOGLE_SEARCH_API_KEY",
        "google.search-engine-id": "$GOOGLE_SEARCH_ENGINE_ID",
        "webUrl": "$WEB_URL"
      }'

    networks:
      - backend
      - frontend

    ports:
      - "$BACKEND_PORT:8080"

  web:
    depends_on:
      - backend

    env_file: .env
    environment:
      NEXT_PUBLIC_BACKEND_URL: $NEXT_PUBLIC_BACKEND_URL

    build:
      context: ./web

    restart: unless-stopped

    networks:
      - frontend

    ports:
      - "$WEB_PORT:3000"

volumes:
  mongodb:

networks:
  frontend:
    driver: bridge

  backend:
    driver: bridge
