spring.application.name=backend

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=plantpatrol

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=backend_consumer
spring.kafka.bootstrap-servers=localhost:9092

security.jwt.secret-key=e1657dfbb5cd2bca9a3c94aafcfaf3537cdf387baa3db25761ab8eb1c0054fa8
security.jwt.expiration-time=86400000

springdoc.api-docs.path=/api/v1/docs

gemini.api-key=AIzaSyAQUVQuor0MD7dgF7MnUvnIWgVxGDO95dg
google.search-api-key=AIzaSyBhLvXBI8ba9Sqr7FZIhrBOqoKfv_ImpuU
google.search-engine-id=a5552c9ca8e75452b

webUrl=http://localhost:3000

# Credentials (not used yet)
#spring.data.mongodb.username=admin
#spring.data.mongodb.password=password
