spring.application.name=backend

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=plantpatrol


security.jwt.secret-key=e1657dfbb5cd2bca9a3c94aafcfaf3537cdf387baa3db25761ab8eb1c0054fa8
security.jwt.expiration-time=3600000

# Credentials (not used yet)
#spring.data.mongodb.username=admin
#spring.data.mongodb.password=password
